amlak/amlak/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

amlak/config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('properties.urls')),
]


# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

amlak/properties/urls.py
from django.urls import path
from django.contrib.auth import views

from django.contrib.auth import views as auth_views

from .views import index_view, properties_view, property_single_view,\
    AboutView,ContactCreate, UserCreate, UpdateUser, mark_messages_as_read,\
    PostsView, property_create, property_update


app_name = 'properties'
urlpatterns = [
    path('', index_view, name='index'),
    path('properties/', properties_view, name='properties'),
    path('properties/<int:pk>', property_single_view, name='proprty_single'),

    # other pages    about, contact
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactCreate.as_view(), name='contact'),

    # cms
    path('account/', UpdateUser.as_view(), name='account'),
    path('account/messages/', mark_messages_as_read, name='messages'),
    path('account/posts/', PostsView.as_view(), name='posts'),
    path('account/posts/create', property_create, name='create'),
    path('account/posts/<int:pk>/update', property_update, name='update'),

]

# login urls
urlpatterns += [
    path("login/", views.LoginView.as_view(), name="login"),
    path("register/", UserCreate.as_view(), name="register"),
    path("logout/", views.LogoutView.as_view(), name="logout"),

]

amlak/properties/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


# multiple select field



# Create your models here.







class Category(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.title

class Equipment(models.Model):
    name = models.CharField(max_length=100, unique=True)
    icon = models.FileField(upload_to="icons/", blank=True, null=True)

    def __str__(self):
        return self.name

class Property(models.Model):
    title = models.CharField(max_length=100, verbose_name=_("عنوان"))
    location = models.CharField(max_length=150, verbose_name=_("آدرس"))
    built_year = models.IntegerField(null=True, verbose_name=_("سال ساخت"))
    class TypeChoices(models.TextChoices):
        apartment = 'آپارتمان',
        house = 'خانه'
    property_type = models.CharField(max_length=50, choices=TypeChoices, default=TypeChoices.apartment, verbose_name=_("نوع"))
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, verbose_name=_("دسته بندی"))
    status = models.CharField(max_length=100, verbose_name=_("وضعیت"))
    bedroom = models.IntegerField(verbose_name=_("اتاق خواب"))
    bathroom = models.IntegerField( verbose_name=_("دستشویی"))
    description = models.TextField(null=True, verbose_name=_("توضیحات"))
    price = models.BigIntegerField(verbose_name=_("قیمت"))
    post_date = models.DateTimeField(null=True, blank=True, verbose_name=_("تاریخ پست"))
    floors = models.IntegerField(null=True, verbose_name=_("تعداد طبقات"))
    parking = models.BooleanField(null=True, verbose_name=_("پارکینگ"))
    lot_area = models.IntegerField(verbose_name=_("متراژ کل"))
    floor_area = models.IntegerField(null=True, verbose_name=_("متراژ سازه"))
    elevator = models.BooleanField(null=True, default=False, verbose_name=_("آسانسور"))
    warehouse = models.BooleanField(null=True, default=False, verbose_name=_("انباری"))
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name=_("کاربر"))
    is_approved = models.BooleanField(default=False, verbose_name=_("وضعیت تایید"))
    is_special = models.BooleanField(default=False, verbose_name=_("برای کاربران ویژه"))
    equipment = models.ManyToManyField(Equipment, blank=True, null=True)


    def save(self, *args, **kwargs):
        if self.is_approved and self.post_date is None:
            self.post_date = timezone.now()

        super().save(*args, **kwargs)





    def thumbnail(self):
        first_image = self.images.first()
        return first_image.image.url if first_image else None


    def __str__(self):
        return f"{self.lot_area}متر in {self.location}"


class Image(models.Model):
    property = models.ForeignKey(Property, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='property/')

    def __str__(self):
        return f"image for {self.property.title}"



# CONTACT MODEL
class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=254)
    subject = models.CharField(max_length=100)
    message = models.TextField()

    def __str__(self):
        return f"{self.name} : {self.subject}"


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='messages')
    content = models.TextField()
    is_read = models.BooleanField(default=False)  # وضعیت خواندن پیام
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Message for {self.user.username} - Read: {self.is_read}"

amlak/properties/forms.py
from django import forms
from .models import Property, Image


class PropertyForm(forms.ModelForm):
    class Meta:
        model = Property
        fields = [
            'title', 'location', 'built_year', 'category',
            'status', 'bedroom', 'bathroom', 'description', 'price',
            'floors', 'parking', 'lot_area', 'floor_area', 'elevator',
            'warehouse', 'equipment', 'user', 'is_approved', 'is_special'
        ]

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(PropertyForm, self).__init__(*args, **kwargs)

        if user and not user.is_superuser:
            self.fields.pop('user')
            self.fields.pop('is_approved')
            self.fields.pop('is_special')


class PropertyImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['image']

amlak/properties/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404

from django.db.models import Count, Q
from django.contrib.auth.models import User
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.utils import timezone

from django.views.generic import ListView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Property, Category, Contact, Message, Image
from .forms import PropertyForm
# Create your views here.


# global site title
sitename = "املاک امیر شاهان"

# put global phone number here
admin_tel= "09123336677"


def index_view(request):
    properties = Property.objects.prefetch_related('images').filter(is_approved=True).order_by('-post_date')[:6]
    special_properties = Property.objects.none()
    if request.user.is_staff:
        special_properties = Property.objects.prefetch_related('images').filter(is_approved=True, is_special=True).order_by('-post_date')
    last_tree_properties = properties[:3]
    context = {
        'properties': properties,
        'special_properties' : special_properties,
        'last_tree_properties':last_tree_properties,
        'sitename': sitename,
        'admin_tel' : admin_tel,
    }
    return render(request, 'properties/index.html', context)

def properties_view(request):
    # Get filter parameters
    title = request.GET.get('title', '')
    location = request.GET.get('location', '')
    property_type = request.GET.get('property_type', '')
    category = request.GET.get('category', '')
    status = request.GET.get('status', '')
    min_bedroom = int(request.GET.get('min_bedroom', 0)) if request.GET.get('min_bedroom') else 0
    min_bathroom = int(request.GET.get('min_bathroom', 0)) if request.GET.get('min_bathroom') else 0
    min_price = int(request.GET.get('min_price', 0)) if request.GET.get('min_price') else 0
    max_price = int(request.GET.get('max_price', 0)) if request.GET.get('max_price') else 0
    min_area = int(request.GET.get('min_area', 0)) if request.GET.get('min_area') else 0
    max_area = int(request.GET.get('max_area', 0)) if request.GET.get('max_area') else 0

    # Base query
    if request.user.is_staff or request.user.is_superuser:
        properties = Property.objects.prefetch_related('images').filter(is_approved=True)
    else:
        properties = Property.objects.prefetch_related('images').filter(is_approved=True, is_special=False)

    # Apply filters dynamically
    if title:
        properties = properties.filter(title__icontains=title)
    if location:
        properties = properties.filter(location__icontains=location)
    if property_type:
        properties = properties.filter(property_type__exact=type)  # Use `exact` for non-text fields
    if category:
        properties = properties.filter(category__title__icontains=category)
    if status:
        properties = properties.filter(status__icontains=status)
    if min_bedroom:
        properties = properties.filter(bedroom__gte=min_bedroom)
    if min_bathroom:
        properties = properties.filter(bathroom__gte=min_bathroom)
    if min_price:
        properties = properties.filter(price__gte=min_price)
    if max_price:
        properties = properties.filter(price__lte=max_price)
    if min_area:
        properties = properties.filter(lot_area__gte=min_area)
    if max_area:
        properties = properties.filter(lot_area__lte=max_area)

    # Order the results
    properties = properties.order_by('-post_date')

    context = {
        'properties': properties,
        'sitename': sitename,
        'admin_tel' : admin_tel,
    }
    return render(request, 'properties/property_list.html', context)



def property_single_view(request, pk):
    property = get_object_or_404(Property.objects.filter(is_approved=True), pk=pk)
    relateds = Property.objects.filter(property_type=property.property_type).exclude(id=property.id)[:2]
    categories = Category.objects.annotate(
        property_count=Count('property', filter=Q(property__is_approved=True))
    ).filter(property_count__gt=0)
    context = {
         'property': property,
         'relateds':relateds,
         'categories': categories,
         'admin_tel' : admin_tel,
         'sitename': sitename,
    }
    return render(request, 'properties/property_single.html', context)

# PAGES *ABOUT *CONTACT US VIEW

class AboutView(ListView):
    model = Property
    template_name = 'properties/about.html'


class ContactCreate(CreateView):
    model = Contact
    fields = "__all__"
    template_name = 'properties/contact.html'
    success_url = reverse_lazy('properties:contact')

    def form_valid(self, form):
        messages.success(self.request, "پیام ارسال شد")
        return super().form_valid(form)

# register user
class UserCreate(CreateView):
    model = User
    fields = ['username', 'password', 'first_name', 'last_name']
    success_url = '/login'

    def form_valid(self, form):
        user = form.save(commit=False)
        user.set_password(form.cleaned_data['password'])
        user.save()
        return super().form_valid(form)



# Dashboard views
def dashboard_view(request):
    return(request, "cms/dashboard.html", {'sitename' : sitename})
# update user and notification sign
class UpdateUser(LoginRequiredMixin,UpdateView):
    model = User
    template_name = 'cms/information_form.html'
    fields = ['username', 'first_name', 'last_name', 'email']
    success_url = reverse_lazy('properties:information')

    def get_object(self, queryset=None):
        # Fetch the User instance of the currently logged-in user
        return get_object_or_404(User, pk=self.request.user.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Add unread messages to the context
        context['unread_messages'] = self.request.user.messages.filter(is_read=False)
        return context

# user posts
class PostsView(LoginRequiredMixin,ListView):
    model = Property
    template_name = 'cms/posts.html'
    context_object_name = 'posts'

    def get_queryset(self):
        queryset = Property.objects.prefetch_related('images').all().order_by('-post_date')
        if self.request.user.is_superuser:
            return queryset
        return queryset.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_date = timezone.now()

        for post in context['posts']:
            if post.post_date:
                post.days_difference = (current_date - post.post_date).days
        return context


@receiver(pre_save, sender=Property)
def save_previous_approval_status(sender, instance, **kwargs):

    if instance.pk:
        previous_instance = Property.objects.get(pk=instance.pk)
        instance.previous_is_approved = previous_instance.is_approved
    else:
        instance.previous_is_approved = False  # مقدار پیش‌فرض برای موارد جدید

@receiver(post_save, sender=Property)
def create_message_on_post_approval(sender, instance, created, **kwargs):
    # بررسی کنید که تایید شده باشد و مقدار قبلی تایید نشده باشد
    if instance.is_approved and not instance.previous_is_approved and not created:
        if not instance.user.is_superuser:
            Message.objects.create(
                user=instance.user,
                content=f"آگهی شما با عنوان «{instance.title}» تایید شد!"
            )
        else:
            Message.objects.create(user=instance.user,
                                content=f"شما آکهی «{instance.title}» را تایید کردید!"
            )


def mark_messages_as_read(request):
    request.user.messages.filter(is_read=False).update(is_read=True)
    return render(request, 'cms/messages.html', {'messages': request.user.messages.all()})


def property_create(request):
    if request.method == 'POST':
        property_form = PropertyForm(request.POST, user=request.user)
        images = request.FILES.getlist('images')
        if property_form.is_valid():
            property_obj = property_form.save(commit=False)
            property_obj.user = request.user
            property_obj.save()

            for image in images:
                Image.objects.create(property=property_obj, image=image)

            return redirect('/account/posts')
    else:
        property_form = PropertyForm(user=request.user)

    return render(request, 'cms/property_form.html', {'property_form': property_form})


def property_update(request, pk):
    property_instance = get_object_or_404(Property, pk=pk)
    if request.method == 'POST':
        property_form = PropertyForm(request.POST, instance=property_instance)
        if property_form.is_valid():
            if not request.user.is_superuser:
                property_instance = property_form.save(commit=False)
                property_instance.is_approved = False  # Set approval to False
                property_instance.save()
            else:
                property_instance = property_form.save()
            for file in request.FILES.getlist('image'):
                Image.objects.create(property=property_instance, image=file)
            return redirect('/account/posts', pk=property_instance.pk)
    else:
        property_form = PropertyForm(instance=property_instance)

    return render(request, 'cms/property_form.html', {
        'property_form': property_form,
        'property': property_instance,
        'admin_tel' : admin_tel,
        'sitename': sitename,
    })

amlak/properties/templates/cms/dashboard.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>داشبورد</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'dashboard/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bbootstrap 4 -->
  <link rel="stylesheet" href="{% static 'dashboard/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'dashboard/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static 'dashboard/plugins/jqvmap/jqvmap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dashboard/dist/adminlte.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'dashboard/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static 'dashboard/plugins/daterangepicker/daterangepicker.css' %}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static 'dashboard/plugins/summernote/summernote-bs4.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <!-- Bootstrap 4 RTL -->
  <link rel="stylesheet" href="https://cdn.rtlcss.com/bootstrap/v4.2.1/css/bootstrap.min.css">
  <!-- Custom style for RTL -->
  <link rel="stylesheet" href="{% static 'dashboard/dist/custom.css' %}">


  <!--VAZIR FONT-->
  {% include "partials/vazir_font.html" %}
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
   <a href="{% url 'properties:index' %}">صفحه اصلی</a>
  </nav>
  <!-- /.navbar -->
  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{% url 'properties:index' %}" class="brand-link">
      <span class="brand-text font-weight-light ml-3">املاک دادرس</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
        <img src="{% static 'dashboard/dist/img/user2-160x160.jpg' %}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <span class="d-block text-light " >{{request.user.get_full_name}}</span>
        </div>
      </div>

      <!-- Sidebar Menu -->

      <!-- Add icons to the links using the .nav-icon class
      with font-awesome or any other icon font library -->
      <div class="nav nav-pills nav-sidebar flex-column">
        <li class="nav-item">
          <a href="{% url 'properties:account' %}" class="nav-link {% if request.path ==  '/account/' %}active{% endif %}">
            <i class="nav-icon fas fa-copy"></i>
              <p>
              اطلاعات حساب
              </p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'properties:posts' %}" class="nav-link">
            <i class="nav-icon fas fa-copy"></i>
              <p>
            {% if request.user.is_superuser %}
              آگهی ها
            {% else %}
              آگهی های من
            {% endif %}
              </p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'properties:create' %}" class="nav-link">
            <i class="nav-icon far fa-plus-square"></i>
            <p>
              آکهی جدید
            </p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'properties:messages' %}" class="nav-link">
            <i class="nav-icon far fa-envelope"></i>
            <p>
              پیام ها
              {% if unread_messages.count > 0 %}
              <span class="right badge badge-danger">جدید</span>
              {% endif %}
            </p>
          </a>
        </li>
      </div>

      </div>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <!-- /.content-wrapper -->
  <div class="content-wrapper">
    <div class="content">
    {% block title %}{% endblock title %}
    {% block main %}{% endblock main %}
    </div>
  </div>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'dashboard/plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'dashboard/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 rtl -->
<script src="https://cdn.rtlcss.com/bootstrap/v4.2.1/js/bootstrap.min.js"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'dashboard/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- ChartJS -->
<script src="{% static 'dashboard/plugins/chart.js/Chart.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'dashboard/plugins/sparklines/sparkline.js' %}"></script>
<!-- JQVMap -->
<script src="{% static 'dashboard/plugins/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/jqvmap/maps/jquery.vmap.world.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'dashboard/plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'dashboard/plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'dashboard/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- Summernote -->
<script src="{% static 'dashboard/plugins/summernote/summernote-bs4.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'dashboard/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dashboard/dist/js/adminlte.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'dashboard/dist/js/pages/dashboard.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dashboard/dist/js/demo.js' %}"></script>
</body>
</html>

amlak/properties/templates/cms/information_form.html
{% extends "cms/dashboard.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load persian_filters %}

{% block title %}
<h2 class="mr-3 mt-3">اطلاعات حساب من</h2>
{% endblock title %}
{% block main %}
<form method="post" class="mt-4">
    {% csrf_token %}
    {% crispy form %}
    <button class="btn btn-block btn-info" type="submit">تایید</button>
</form>
{% endblock main %}

amlak/properties/templates/cms/messages.html
{% extends "cms/dashboard.html" %}
{% load persian_filters %}

{% block title %}
<h3 class="mb-3 ">پیام ها</h3>
{% endblock title %}

{% block main %}

<ul dir="rtl">
    {% for message in messages %}
    <li class="mb-2 mt-2">{{message.content}}</li>
    {% endfor %}
</ul>
{% endblock main %}

amlak/properties/templates/cms/posts.html
{% extends "cms/dashboard.html" %}

{% load static %}
{% load persian_filters %}

{% block main %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>کارت‌های آگهی املاک</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5 mb-5">
        <h2 class="text-left mb-4">آگهی‌های من</h2>
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% if posts %}
                {% for obj in posts %}
                <div class="col">
                    <div class="card h-100">
                        <img src="{{obj.thumbnail}}" class="card-img-top" alt="عکس ملک" style="height:200px;">
                        <div class="card-body">
                            <div class="d-flex align-items-center justify-content-between">
                                <h4 class="card-title">{{obj.title|persian_numbers}}</h4>
                                <p class="card-text">{% if obj.is_approved %}{{obj.days_difference|persian_numbers}} روز قبل {% else %} <p class="text-warning">در حال بررسی</p> {% endif %}</p>
                            </div>
                            <div class="d-flex align-items-center justify-content-between mt-3">
                                <a href="{{obj.pk}}/update" class="btn btn-primary">ویرایش</a>
                                <p class="card-text">{{obj.price|persian_numbers    }} تومان </p>
                            </div>
                            {% if request.user.is_superuser %}
                                <p class="text-right">کاربر:{{obj.user}}</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            {% else %}
            <div class="d-flex justify-content-center">
                <p class="text-center">محتوایی برای نمایش وجود ندارد</p>
            </div>
            {% endif %}
        </div>
    </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

{% endblock main %}

amlak/properties/templates/cms/property_form.html
{% extends "cms/dashboard.html" %}
{% load static %}
{% load persian_filters %}
{% load crispy_forms_tags %}

{% block title %} <h3 class="mb-3 mt-3">آگهی جدید</h3> {% endblock title %}

{% block main %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{property_form|crispy}}
    <label for="images">Upload Images:</label>
    <input type="file" name="images" multiple>

    <button class="btn btn-block btn-primary mb-4 mt-4" type="submit">تایید</button>
</form>
{% endblock main %}