amlak/amlak/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

amlak/config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('properties.urls')),
]


# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

amlak/properties/urls.py
from django.urls import path
from django.contrib.auth import views

from django.contrib.auth import views as auth_views

from .views import index_view, properties_view, property_single_view,\
    AboutView,ContactCreate, UserCreate, UpdateUser, mark_messages_as_read,\
    PostsView, property_create, property_update


app_name = 'properties'
urlpatterns = [
    path('', index_view, name='index'),
    path('properties/', properties_view, name='properties'),
    path('properties/<int:pk>', property_single_view, name='proprty_single'),

    # other pages    about, contact
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactCreate.as_view(), name='contact'),

    # cms
    path('account/', UpdateUser.as_view(), name='account'),
    path('account/messages/', mark_messages_as_read, name='messages'),
    path('account/posts/', PostsView.as_view(), name='posts'),
    path('account/posts/create', property_create, name='create'),
    path('account/posts/<int:pk>/update', property_update, name='update'),

]

# login urls
urlpatterns += [
    path("login/", views.LoginView.as_view(), name="login"),
    path("register/", UserCreate.as_view(), name="register"),
    path("logout/", views.LogoutView.as_view(), name="logout"),

]

amlak/properties/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


# multiple select field



# Create your models here.







class Category(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.title

class Equipment(models.Model):
    name = models.CharField(max_length=100, unique=True)
    icon = models.FileField(upload_to="icons/", blank=True, null=True)

    def __str__(self):
        return self.name

class Property(models.Model):
    title = models.CharField(max_length=100, verbose_name=_("عنوان"))
    location = models.CharField(max_length=150, verbose_name=_("آدرس"))
    built_year = models.IntegerField(null=True, verbose_name=_("سال ساخت"))
    class TypeChoices(models.TextChoices):
        apartment = 'آپارتمان',
        house = 'خانه'
    property_type = models.CharField(max_length=50, choices=TypeChoices, default=TypeChoices.apartment, verbose_name=_("نوع"))
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, verbose_name=_("دسته بندی"))
    status = models.CharField(max_length=100, verbose_name=_("وضعیت"))
    bedroom = models.IntegerField(verbose_name=_("اتاق خواب"))
    bathroom = models.IntegerField( verbose_name=_("دستشویی"))
    description = models.TextField(null=True, verbose_name=_("توضیحات"))
    price = models.BigIntegerField(verbose_name=_("قیمت"))
    post_date = models.DateTimeField(null=True, blank=True, verbose_name=_("تاریخ پست"))
    floors = models.IntegerField(null=True, verbose_name=_("تعداد طبقات"))
    parking = models.BooleanField(null=True, verbose_name=_("پارکینگ"))
    lot_area = models.IntegerField(verbose_name=_("متراژ کل"))
    floor_area = models.IntegerField(null=True, verbose_name=_("متراژ سازه"))
    elevator = models.BooleanField(null=True, default=False, verbose_name=_("آسانسور"))
    warehouse = models.BooleanField(null=True, default=False, verbose_name=_("انباری"))
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name=_("کاربر"))
    is_approved = models.BooleanField(default=False, verbose_name=_("وضعیت تایید"))
    is_special = models.BooleanField(default=False, verbose_name=_("برای کاربران ویژه"))
    equipment = models.ManyToManyField(Equipment, blank=True, null=True)


    def save(self, *args, **kwargs):
        if self.is_approved and self.post_date is None:
            self.post_date = timezone.now()

        super().save(*args, **kwargs)





    def thumbnail(self):
        first_image = self.images.first()
        return first_image.image.url if first_image else None


    def __str__(self):
        return f"{self.lot_area}متر in {self.location}"


class Image(models.Model):
    property = models.ForeignKey(Property, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='property/')

    def __str__(self):
        return f"image for {self.property.title}"



# CONTACT MODEL
class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=254)
    subject = models.CharField(max_length=100)
    message = models.TextField()

    def __str__(self):
        return f"{self.name} : {self.subject}"


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='messages')
    content = models.TextField()
    is_read = models.BooleanField(default=False)  # وضعیت خواندن پیام
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Message for {self.user.username} - Read: {self.is_read}"

amlak/properties/forms.py
from django import forms
from .models import Property, Image


class PropertyForm(forms.ModelForm):
    class Meta:
        model = Property
        fields = [
            'title', 'location', 'built_year', 'category',
            'status', 'bedroom', 'bathroom', 'description', 'price',
            'floors', 'parking', 'lot_area', 'floor_area', 'elevator',
            'warehouse', 'equipment', 'user', 'is_approved', 'is_special'
        ]

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(PropertyForm, self).__init__(*args, **kwargs)

        if user and not user.is_superuser:
            self.fields.pop('user')
            self.fields.pop('is_approved')
            self.fields.pop('is_special')


class PropertyImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['image']

amlak/properties/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404

from django.db.models import Count, Q
from django.contrib.auth.models import User
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.utils import timezone

from django.views.generic import ListView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Property, Category, Contact, Message, Image
from .forms import PropertyForm
# Create your views here.


# global site title
sitename = "املاک امیر شاهان"

# put global phone number here
admin_tel= "09123336677"


def index_view(request):
    properties = Property.objects.prefetch_related('images').filter(is_approved=True).order_by('-post_date')[:6]
    special_properties = Property.objects.none()
    if request.user.is_staff:
        special_properties = Property.objects.prefetch_related('images').filter(is_approved=True, is_special=True).order_by('-post_date')
    last_tree_properties = properties[:3]
    context = {
        'properties': properties,
        'special_properties' : special_properties,
        'last_tree_properties':last_tree_properties,
        'sitename': sitename,
        'admin_tel' : admin_tel,
    }
    return render(request, 'properties/index.html', context)

def properties_view(request):
    # Get filter parameters
    title = request.GET.get('title', '')
    location = request.GET.get('location', '')
    property_type = request.GET.get('property_type', '')
    category = request.GET.get('category', '')
    status = request.GET.get('status', '')
    min_bedroom = int(request.GET.get('min_bedroom', 0)) if request.GET.get('min_bedroom') else 0
    min_bathroom = int(request.GET.get('min_bathroom', 0)) if request.GET.get('min_bathroom') else 0
    min_price = int(request.GET.get('min_price', 0)) if request.GET.get('min_price') else 0
    max_price = int(request.GET.get('max_price', 0)) if request.GET.get('max_price') else 0
    min_area = int(request.GET.get('min_area', 0)) if request.GET.get('min_area') else 0
    max_area = int(request.GET.get('max_area', 0)) if request.GET.get('max_area') else 0

    # Base query
    if request.user.is_staff or request.user.is_superuser:
        properties = Property.objects.prefetch_related('images').filter(is_approved=True)
    else:
        properties = Property.objects.prefetch_related('images').filter(is_approved=True, is_special=False)

    # Apply filters dynamically
    if title:
        properties = properties.filter(title__icontains=title)
    if location:
        properties = properties.filter(location__icontains=location)
    if property_type:
        properties = properties.filter(property_type__exact=type)  # Use `exact` for non-text fields
    if category:
        properties = properties.filter(category__title__icontains=category)
    if status:
        properties = properties.filter(status__icontains=status)
    if min_bedroom:
        properties = properties.filter(bedroom__gte=min_bedroom)
    if min_bathroom:
        properties = properties.filter(bathroom__gte=min_bathroom)
    if min_price:
        properties = properties.filter(price__gte=min_price)
    if max_price:
        properties = properties.filter(price__lte=max_price)
    if min_area:
        properties = properties.filter(lot_area__gte=min_area)
    if max_area:
        properties = properties.filter(lot_area__lte=max_area)

    # Order the results
    properties = properties.order_by('-post_date')

    context = {
        'properties': properties,
        'sitename': sitename,
        'admin_tel' : admin_tel,
    }
    return render(request, 'properties/property_list.html', context)



def property_single_view(request, pk):
    property = get_object_or_404(Property.objects.filter(is_approved=True), pk=pk)
    relateds = Property.objects.filter(property_type=property.property_type).exclude(id=property.id)[:2]
    categories = Category.objects.annotate(
        property_count=Count('property', filter=Q(property__is_approved=True))
    ).filter(property_count__gt=0)
    context = {
         'property': property,
         'relateds':relateds,
         'categories': categories,
         'admin_tel' : admin_tel,
         'sitename': sitename,
    }
    return render(request, 'properties/property_single.html', context)

# PAGES *ABOUT *CONTACT US VIEW

class AboutView(ListView):
    model = Property
    template_name = 'properties/about.html'


class ContactCreate(CreateView):
    model = Contact
    fields = "__all__"
    template_name = 'properties/contact.html'
    success_url = reverse_lazy('properties:contact')

    def form_valid(self, form):
        messages.success(self.request, "پیام ارسال شد")
        return super().form_valid(form)

# register user
class UserCreate(CreateView):
    model = User
    fields = ['username', 'password', 'first_name', 'last_name']
    success_url = '/login'

    def form_valid(self, form):
        user = form.save(commit=False)
        user.set_password(form.cleaned_data['password'])
        user.save()
        return super().form_valid(form)



# Dashboard views
def dashboard_view(request):
    return(request, "cms/dashboard.html", {'sitename' : sitename})
# update user and notification sign
class UpdateUser(LoginRequiredMixin,UpdateView):
    model = User
    template_name = 'cms/information_form.html'
    fields = ['username', 'first_name', 'last_name', 'email']
    success_url = reverse_lazy('properties:information')

    def get_object(self, queryset=None):
        # Fetch the User instance of the currently logged-in user
        return get_object_or_404(User, pk=self.request.user.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Add unread messages to the context
        context['unread_messages'] = self.request.user.messages.filter(is_read=False)
        return context

# user posts
class PostsView(LoginRequiredMixin,ListView):
    model = Property
    template_name = 'cms/posts.html'
    context_object_name = 'posts'

    def get_queryset(self):
        queryset = Property.objects.prefetch_related('images').all().order_by('-post_date')
        if self.request.user.is_superuser:
            return queryset
        return queryset.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_date = timezone.now()

        for post in context['posts']:
            if post.post_date:
                post.days_difference = (current_date - post.post_date).days
        return context


@receiver(pre_save, sender=Property)
def save_previous_approval_status(sender, instance, **kwargs):

    if instance.pk:
        previous_instance = Property.objects.get(pk=instance.pk)
        instance.previous_is_approved = previous_instance.is_approved
    else:
        instance.previous_is_approved = False  # مقدار پیش‌فرض برای موارد جدید

@receiver(post_save, sender=Property)
def create_message_on_post_approval(sender, instance, created, **kwargs):
    # بررسی کنید که تایید شده باشد و مقدار قبلی تایید نشده باشد
    if instance.is_approved and not instance.previous_is_approved and not created:
        if not instance.user.is_superuser:
            Message.objects.create(
                user=instance.user,
                content=f"آگهی شما با عنوان «{instance.title}» تایید شد!"
            )
        else:
            Message.objects.create(user=instance.user,
                                content=f"شما آکهی «{instance.title}» را تایید کردید!"
            )


def mark_messages_as_read(request):
    request.user.messages.filter(is_read=False).update(is_read=True)
    return render(request, 'cms/messages.html', {'messages': request.user.messages.all()})


def property_create(request):
    if request.method == 'POST':
        property_form = PropertyForm(request.POST, user=request.user)
        images = request.FILES.getlist('images')
        if property_form.is_valid():
            property_obj = property_form.save(commit=False)
            property_obj.user = request.user
            property_obj.save()

            for image in images:
                Image.objects.create(property=property_obj, image=image)

            return redirect('/account/posts')
    else:
        property_form = PropertyForm(user=request.user)

    return render(request, 'cms/property_form.html', {'property_form': property_form})


def property_update(request, pk):
    property_instance = get_object_or_404(Property, pk=pk)
    if request.method == 'POST':
        property_form = PropertyForm(request.POST, instance=property_instance)
        if property_form.is_valid():
            if not request.user.is_superuser:
                property_instance = property_form.save(commit=False)
                property_instance.is_approved = False  # Set approval to False
                property_instance.save()
            else:
                property_instance = property_form.save()
            for file in request.FILES.getlist('image'):
                Image.objects.create(property=property_instance, image=file)
            return redirect('/account/posts', pk=property_instance.pk)
    else:
        property_form = PropertyForm(instance=property_instance)

    return render(request, 'cms/property_form.html', {
        'property_form': property_form,
        'property': property_instance,
        'admin_tel' : admin_tel,
        'sitename': sitename,
    })

amlak/properties/templates/properties/about.html
{% extends "properties/index.html" %}
{% load static %}
{% load persian_filters %}

{% block main %}

<div class="hero-wrap" style="background-image: url('{% static 'amlak/images/bg_1.jpg' %}');">
    <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text align-items-center justify-content-center">
                <div class="col-md-9 ftco-animate text-center">
                    <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'properties:index' %}">خانه</a></span> <span>درباره‌ما</span></p>
                    <h1 class="mb-3 bread">درباره‌ما</h1>
                </div>
            </div>
        </div>
    </div>
    <section class="ftco-section ftc-no-pb" dir="rtl">
        <div class="container">
            <div class="row no-gutters">
                <div class="col-md-5 p-md-5 img img-2 d-flex justify-content-center align-items-center" style="background-image: url(images/about.jpg);">
                    <a href="https://vimeo.com/45830194" class="icon popup-vimeo d-flex justify-content-center align-items-center">
                        <span class="icon-play"></span>
                    </a>
                </div>
            <div class="col-md-7 wrap-about pb-md-5 ftco-animate">
                <div class="heading-section heading-section-wo-line mb-5 pl-md-5">
                    <div class="pl-md-5 ml-md-5 text-right">
                        <span class="subheading">بررسی کلی آژانس املاک کیهان</span>
                        <h2 class="mb-4">با قوانین آشنا شوید</h2>
                    </div>
                </div>
                <div class="pl-md-5 ml-md-5 mb-5 text-right" dir="rtl">
                    <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.</p>
                    <p><a href="#" class="btn-custom">بیشتر بدانید</a></p>
                </div>
            </div>
        </div>
    </div>
    </section>

    {% include "partials/facts.html" %}


    {% include "partials/testimontial.html" %}

{% endblock main %}

amlak/properties/templates/properties/contact.html
{% extends "properties/index.html" %}
{% load static %}
{% load persian_filters %}

{% block main %}

<!--START MAIN-->
<div class="hero-wrap" style="background-image: url('images/bg_1.jpg');">
  <div class="overlay"></div>
  <div class="container">
    <div class="row no-gutters slider-text align-items-center justify-content-center">
      <div class="col-md-9 ftco-animate text-center">
        <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'properties:index' %}">خانه</a></span> <span>تماس‌باما</span></p>
        <h1 class="mb-3 bread">تماس باما</h1>
      </div>
    </div>
  </div>
</div>

<section class="ftco-section contact-section bg-light" dir="rtl">
  <div class="container">
    <div class="row d-flex mb-5 contact-info">
      <div class="col-md-12 mb-4 text-right">
        <h2 class="h3">اطلاعات تماس</h2>
      </div>
      <div class="w-100"></div>
      <div class="col-md-3 d-flex text-right">
        <div class="info bg-white p-4">
          <p><span>آدرس:</span> <span class="text-dark">تهران، بلوار فردوسی نبش خیابان مولوی</span></p>
        </div>
      </div>
      <div class="col-md-3 d-flex text-right">
        <div class="info bg-white p-4">
          <p><span>شماره تماس:</span> <a href="tel://1234567920">{{2132122|persian_numbers}}+</a></p>
        </div>
      </div>
      <div class="col-md-3 d-flex text-right">
        <div class="info bg-white p-4">
          <p><span>ایمیل:</span> <a href="mailto:info@yoursite.com">info@yoursite.com</a></p>
        </div>
      </div>
      
    </div>
    <div class="row block-9">
      <div class="col-md-6 order-md-last d-flex">
        <form class="bg-white p-5 contact-form" id="form" method="post" action='{% url "properties:contact" %}#form'>
            {% csrf_token %}
          <div class="form-group">
            <input type="text" name=name class="form-control" placeholder="نام شما">
          </div>
          <div class="form-group">
            <input type="text" name=email class="form-control" placeholder="ایمیل شمل">
          </div>
          <div class="form-group">
            <input type="text" name=subject class="form-control" placeholder="موضوع">
          </div>
          <div class="form-group">
            <textarea name="message" cols="30" rows="7" class="form-control" placeholder="پیام"></textarea>
          </div>
          <div class="form-group text-right">
            <input type="submit" value="ارسال پیام" class="btn btn-primary py-3 px-5">
          </div>
            <!-- MESSAGE FOR SENDING MESSAGE SUCCSECFULLY -->
            <div class="text-info text-right">
            {% if messages %}
                {% for message in messages %}
                    <p>{{message}}</p>
                {% endfor %}
            {% endif %}
            </div>
        </form>
      
      </div>

      <div class="col-md-6 d-flex">
        <div id="map" class="bg-white"></div>
      </div>
    </div>
  </div>
</section>

{% endblock main %}

amlak/properties/templates/properties/property_single.html
{% extends "properties/index.html" %}
{% load static %}
{% load persian_filters %}

{% block main %}



<section class="ftco-section">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <div class="row">
          <div class="col-md-12 ftco-animate">
            <div class="single-slider owl-carousel">
              {% for img in property.images.all %}
              <div class="item">
                <div class="properties-img" style="background-image: url('{{img.image.url}}');"></div>
              </div>
              {% endfor %}
            </div>
          </div>
          <div class="col-md-12 Properties-single mt-4 mb-5 ftco-animate text-right">
            <h2><bold>{{property.title|persian_numbers}}</bold></h2>
            <p class="rate mb-4">
              <span class="loc"><a href="#">{{property.location}}<i class="icon-map"></i></a></span>
            </p>
            <h3 style="font-size: 1.3125rem;font-weight:bold;margin:25px 0;">توضیحات اصلی</h3>
            <div class="d-md-flex mt-5 mb-5 justify-content-end text-dark">
                <ul class="ml-md-5" dir="rtl">
                    <li>
                        <h6> زیربنا: {{property.lot_area|persian_numbers}} متر </h6>
                    </li>
                    <li>
                        <h6>اتاق خواب: {{property.bedroom|persian_numbers}}</h6>
                    </li>
                    <li>
                        <h6>دست‌شویی: {{property.bathroom|persian_numbers}}</h6>
                    </li>
                    <li>
                        <h6>پارکینگ: دارد</h6>
                    </li>
                    <li>
                        <h6>آسانسور: {% if not property.elevator %}نامشخض {% else %}دارد{% endif %}</h6>
                    </li>
                </ul>
                <ul class="ml-md-5 custom-list text-end" dir="rtl">
                    <li>
                        <h6> موقعیت: جنوبی</h6>
                    </li>
                    <li>
                        <h6>نما: سنگ</h6>
                    </li>
                    <li>
                        <h6>کابینت: چوب</h6>
                    </li>
                    <li>
                        <h6>انباری: {% if property.warehouse %}دارد {% else %}ندارد{% endif %}</h6>
                    </li>
                    <li>
                        <h6>سند: 6 دانگ</h6>
                    </li>
                </ul>
                <ul class="ml-md-5 custom-list text-end" dir="rtl">
                    <li>
                        <h6>مساحت سطح طبقه: {% if not property.floor_area %}نامشخص {% else
                            %}{{property.floor_area|persian_numbers}}{% endif %}</h6>
                    </li>
                    <li>
                        <h6>سال ساخت: {{property.built_year|persian_numbers}}</h6>
                    </li>
                    <li>
                        <h6>طبقات: {% if not property.floors %}نامشخص {% else %}{{property.floors|persian_numbers}}{% endif %}</h6>
                    </li>
                    <li>
                        <h6>طبقه: {% if not property.floors %}نامشخص {% else %}{{property.floors|persian_numbers}}{% endif %}</h6>
                    </li>
                    <li>
                        <h6>کفپوش: سرامیک</h6>
                    </li>

                </ul>
            </div>

            <h2 style="font-size: 1.3125rem;font-weight:bold;margin:25px 0">امکانات و تجهیزات</h2>
            <div class="row" dir="rtl">
                {% for item in property.equipment.all %}
                <div class="d-flex align-items-center mt-16 mt-lg-24 col-md-4">
                    <img style="width:20px;height:20px;margin:10px;" src="{{item.icon.url}}" alt=""><span class="text-dark">{{item.name}}</span>
                </div>
                {% endfor %}
            </div>
            <h3 style="font-size: 1.3125rem;font-weight:bold;margin:25px 0;">توضیحات تکمیلی</h3>
            <p>{{property.description|persian_numbers}}</p>
            <!--<p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove, the headline of Alphabet Village and the subline of her own road, the Line Lane. Pityful a rethoric question ran over her cheek, then she continued her way.</p>-->
          <div class="d-flex justify-content-center" style="margin:30px 0;">
            <a href="tel:{{admin_tel}}"style="width:100%;" class="btn btn-dark px-1">تماس بگیرید</a>
          </div>
          </div>
          <div class="col-md-12 properties-single ftco-animate mb-5 mt-5">
            <h4 class="mb-4 text-right">ملک‌های مرتبط</h4>
            <div class="row">
            {% for obj in relateds %}
              <div class="col-md-6 ftco-animate">
                <div class="properties">
                    <a href="#" class="img img-2 d-flex justify-content-center align-items-center" style="background-image: url('{{ obj.thumbnail }}');">
                        <div class="icon d-flex justify-content-center align-items-center">
                            <span class="icon-search2"></span>
                        </div>
                    </a>
                    <div class="text p-3">
                        <span class="status sale">{{obj.status}}</span>
                        <div class="d-flex">
                            <div class="two text-left">
                                <span class="price">{{obj.price|persian_numbers}} <span class="text-black-50 fs-6 text-muted"><small>میلیارد</small></span></span>
                            </div>
                            <div class="one text-right">
                                <h3><a href="property-single.html">{{obj.title|persian_numbers}}</a></h3>
                                <p>{{obj.type}}</p>
                            </div>
                        </div>
                        <p class="text-right">{{obj.description|persian_numbers}}</p>
                        <hr>
                        <p class="bottom-area d-flex">
                            <span><i class="flaticon-selection"></i> {{obj.area|persian_numbers}}متر</span>
                            <span class="ml-auto"><i class="flaticon-bathtub"></i> {{obj.bathroom|persian_numbers}}</span>
                            <span><i class="flaticon-bed"></i> {{obj.bedroom|persian_numbers}}</span>
                        </p>
                    </div>
                </div>
            </div>
            {% endfor %}
            </div>
          </div>

        </div>
      </div> <!-- .col-md-8 -->
      <div class="col-lg-4 sidebar ftco-animate">
        <!--<div class="sidebar-box">
          <form action="#" class="search-form">
            <div class="form-group">
              <span class="icon fa fa-search"></span>
              <input type="text" class="form-control" placeholder="Type a keyword and hit enter">
            </div>
          </form>
        </div>-->
        <div class="ftco-animate text-right">
          <p class="breadcrumbs"><span class="ml-2"><a href="{% url 'properties:index' %}">خانه</a></span> <span class="ml-2"><a href="{% url 'properties:properties' %}">ملک‌ها</a></span> <span class="ml-2">{{property.title|persian_numbers}}</span></p>
        </div>
        <div class="sidebar-box ftco-animate">
          <div class="categories text-right">
            <h3 class="text-end">دسته‌بندی‌ها</h3>
            <ul class="list-unstyled">
              {% for category in categories %}
              <li class="d-flex justify-content-between flex-row-reverse">
                <a href="{% url 'properties:properties' %}?category={{category.title}}" class="text-decoration-none">{{category.title}}</a>
                <span>{{ category.property_count|persian_numbers}}</span>
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>

        <!--<div class="sidebar-box ftco-animate">-->
        <!--  <h3>Tag Cloud</h3>-->
        <!--  <div class="tagcloud">-->
        <!--    <a href="#" class="tag-cloud-link">dish</a>-->
        <!--    <a href="#" class="tag-cloud-link">menu</a>-->
        <!--    <a href="#" class="tag-cloud-link">food</a>-->
        <!--    <a href="#" class="tag-cloud-link">sweet</a>-->
        <!--    <a href="#" class="tag-cloud-link">tasty</a>-->
        <!--    <a href="#" class="tag-cloud-link">delicious</a>-->
        <!--    <a href="#" class="tag-cloud-link">desserts</a>-->
        <!--    <a href="#" class="tag-cloud-link">drinks</a>-->
        <!--  </div>-->
        <!--</div>-->
      </div>
    </div>
  </div>
</section> <!-- .section -->



{% endblock main %}